feat(client): Added FASTLY_USER_AGENT env variable
fastly/go-fastly pull request #531
Opened 2024-06-05 16:01 UTC by jsonroy-fastly

Added the use of a new environment variable that will allow the user to overwrite the default User-Agent of the http client.

2024-06-05 16:03 UTC, Integralist approved these changes

2024-06-05 20:28 UTC, Integralist requested changes
An internal discussion is required before this change can move forward

2024-06-06 13:30 UTC, Integralist approved these changes

2024-06-06 17:17 UTC, sgorbaty approved these changes

2024-06-10 14:10 UTC, merged